import test,{before} from 'node:test';
import assert from 'node:assert/strict';
import supertest from 'supertest';
import {randomUUID} from 'node:crypto';
import {createApp} from '../server/app.mjs';
import {hashPassword} from '../server/passwords.mjs';
const origin='http://localhost:4173',cookie='warehouse_session='+'a'.repeat(64),csrf='b'.repeat(64);
let app,role='manager',failed=0;
const repo={health:async()=>true,session:async()=>({id:randomUUID(),username:'test',role,csrf}),listItems:async()=>({items:[],nextCursor:null}),findUser:async()=>null,failLogin:async()=>{failed++;},clearFailures:async()=>{},startSession:async()=>{},endSession:async()=>{},createItem:async input=>input};
before(async()=>{const hash=await hashPassword('example-password');repo.findUser=async username=>username==='manager'?{id:randomUUID(),username,role:'manager',password_hash:hash}:null;app=await createApp(repo,{origin});});
const auth=req=>req.set('Cookie',cookie).set('Origin',origin).set('X-CSRF-Token',csrf);
test('health responds without a session',async()=>{await supertest(app).get('/api/health').expect(200,{ok:true});});
test('inventory requires a session',async()=>{await supertest(app).get('/api/items').expect(401);});
test('an authenticated request can read inventory',async()=>{await auth(supertest(app).get('/api/items')).expect(200,{items:[],nextCursor:null});});
test('mutations reject an untrusted origin',async()=>{await auth(supertest(app).post('/api/items')).set('Origin','https://another-site.example').send({}).expect(403);});
test('mutations require the session CSRF token',async()=>{await supertest(app).post('/api/items').set('Cookie',cookie).set('Origin',origin).send({}).expect(403);});
test('a viewer cannot add items',async()=>{role='viewer';try{await auth(supertest(app).post('/api/items')).send({}).expect(403);}finally{role='manager';}});
test('a clerk cannot edit item details',async()=>{role='clerk';try{await auth(supertest(app).patch(`/api/items/${randomUUID()}`)).send({}).expect(403);}finally{role='manager';}});
test('invalid item input returns a readable error',async()=>{const r=await auth(supertest(app).post('/api/items')).send({name:'Missing fields'}).expect(400);assert.equal(typeof r.body.error,'string');});
test('invalid page limits are rejected',async()=>{await auth(supertest(app).get('/api/items?limit=10000')).expect(400);});
test('failed login returns a generic error and records a failed attempt',async()=>{await supertest(app).post('/api/login').set('Origin',origin).send({username:'manager',password:'wrong-password'}).expect(401);assert.equal(failed,1);});
test('login sets an HttpOnly SameSite cookie and does not expose the password hash',async()=>{const r=await supertest(app).post('/api/login').set('Origin',origin).send({username:'manager',password:'example-password'}).expect(200);assert.match(r.headers['set-cookie'][0],/HttpOnly/);assert.match(r.headers['set-cookie'][0],/SameSite=Strict/);assert.equal(r.body.user.password_hash,undefined);assert.equal(r.body.csrf.length,64);});
test('API responses are not cacheable',async()=>{const r=await auth(supertest(app).get('/api/items'));assert.equal(r.headers['cache-control'],'no-store');assert.equal(r.headers['x-powered-by'],undefined);});
test('unknown API routes return JSON rather than the app shell',async()=>{await auth(supertest(app).get('/api/not-a-route')).expect(404);});
